/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaredesignproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Ellipse2D;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author rafad
 */
public class DistributionNetworkView extends javax.swing.JFrame implements IView{

    DistributionNetworkController controller;
    /**
     * Creates new form View
     */
    public DistributionNetworkView() {
        initComponents();
    }

    @Override
    public void start() {     
        initComponents();
        this.loadNetworkMap();
    }

    @Override
    public void setController(DistributionNetworkController c) {
        controller = c;
    }
    
    private void loadNetworkMap() {

        JPanel panel = new JPanel(){
            @Override
            public void paintComponent(Graphics g){
                //loadVertexs(g);
                loadEdges(g);
            }
        };  
        loadVertexsButtons(panel);
        panel.setOpaque(true);
        panel.setLayout(null);
        this.setContentPane(panel);
        this.setSize(800, 800);
        this.setLocationByPlatform(true);
        this.setVisible(true);
    }
    
    private void loadVertexsButtons(JPanel p){
        JButton vertex;
        for(Vertex v : controller.getNetworkMap().vertexSet()){
            //vertex = new RoundButton("iep", new ImageIcon("C:\\Users\\rafad\\Desktop\\Rafa\\European Master Software Engineering\\2nd\\Software Design\\SoftwareDesignProject\\color.png"));
            vertex = new JButton();
            vertex.setText("S");
            vertex.setSize(50, 50);
            vertex.setLocation(v.getCoordX(), v.getCoordY());
            vertex.setVisible(true);
            vertex.addActionListener(controller);
            p.add(vertex);
        }
    }
    
    //ACTUALMENTE NO SE USA, se usa la otra, simplemente porque me era mas facil hacer el boton clickable
    private void loadVertexs(Graphics g){

        for(Vertex v : controller.getNetworkMap().vertexSet()){
            
            Ellipse2D oval = new Ellipse2D.Double(v.getCoordX(), v.getCoordY(), 50, 50) {};
            Graphics2D g2d = (Graphics2D) g;
            g2d.setColor(Color.red);
            g2d.fill(oval);
            
            //g.setColor(Color.red);         
            //g.fillOval(v.getCoordX(), v.getCoordY(), 50, 50); 
            
        }

    }
   
    
    private void loadEdges(Graphics g){    
        for(Edge e : controller.getNetworkMap().edgeSet()){
            g.setColor(Color.black);
            g.drawLine(e.getV1().getCenterX(), e.getV1().getCenterY(), e.getV2().getCenterX(), e.getV2().getCenterY());
        }
    }
    
    @Override
    public void setVisibility(boolean v){
        this.setVisible(v);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributionNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributionNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributionNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributionNetworkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributionNetworkView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
